- block:
    - name: "Install guest agent"
      apt:
        name: ['qemu-guest-agent']
        state: present
      become: true

    - name: Disable predictable network names
      replace:
        path: /etc/default/grub
        regexp: 'GRUB_CMDLINE_LINUX=""'
        replace: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
      become: true

    - name: Updating grub
      command: update-grub
      become: true

    when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
