- name: "Install net-tools and ifenslave for supporting bonding"
  apt:
    name: ['ifenslave', 'net-tools']
    state: present
    update_cache: true
  when: ansible_distribution_major_version | int >= 20

- name: "Install netplan.io and clout-init"
  apt:
    name: ['netplan.io', 'cloud-init']
    state: present
    update_cache: true
  when: ansible_distribution != "Ubuntu"

- name: "Add network renderer #1"
  lineinfile:
    path: /etc/cloud/cloud.cfg
    line: "   network:"
    create: yes
  when: ansible_distribution != "Ubuntu"

- name: "Add network renderer #2"
  lineinfile:
    path: /etc/cloud/cloud.cfg
    line: "     renderers: ['netplan', 'eni', 'sysconfig']"
    create: yes
  when: ansible_distribution != "Ubuntu"
