- name: "Install net-tools and ifenslave for supporting bonding"
  apt:
    name: ['ifenslave', 'net-tools']
    state: present
    update_cache: true
  when: ansible_distribution_major_version | int >= 20
