---
- name: Install pip3
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python3-pip

- name: Install JupyterLab and Korean language pack
  pip:
    name:
      - jupyterlab
      - jupyterlab-language-pack-ko-KR
    state: present
    executable: pip3

- name: Generate JupyterLab config
  command: jupyter lab --generate-config
  become: yes
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Set JupyterLab server IP to 0.0.0.0
  lineinfile:
    path: "/home/{{ ansible_env.SUDO_USER }}/.jupyter/jupyter_lab_config.py"
    regexp: "^c.ServerApp.ip"
    line: "c.ServerApp.ip = '0.0.0.0'"

- name: Set JupyterLab server token
  lineinfile:
    path: "/home/{{ ansible_env.SUDO_USER }}/.jupyter/jupyter_lab_config.py"
    regexp: "^c.ServerApp.token"
    line: "c.ServerApp.token = '6c4bfd9ffd59618566557195d0f0a733f246545b8b118ca7'"

- name: "Copy jupyter-lab service"
  template:
    src: etc/systemd/system/jupyterlab.service.j2
    dest: /etc/systemd/system/jupyterlab.service
    owner: root
    group: root
    mode: 0644

- name: Start jupyter lab service
  systemd:
    name: jupyterlab
    enabled: yes
    daemon_reload: yes
    state: started