---
- name: Extract RHEL version from build_name
  set_fact:
    rhel_version: "{{ build_name | regex_search('\\d+$') }}"
  when: ansible_os_family == "RedHat" or ansible_os_family == "Rocky"

- name: Install pip3
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python3-pip
  when: ansible_os_family == "Debian"

- name: Install pip3
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python39-pip
  when: ansible_os_family in ["RedHat", "Rocky"] and ansible_distribution_version is match('^8\\.')

- name: Install pip3
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pip
  when: ansible_os_family in ["RedHat", "Rocky"] and ansible_distribution_version is match('^9\\.')

- name: Install JupyterLab and Korean language pack
  pip:
    name:
      - jupyterlab
      - jupyterlab-language-pack-ko-KR
    state: present
    executable: pip3

- name: Ensure jupyter config directory exists on target
  file:
    path: /home/{{ ansible_env.SUDO_USER }}/.jupyter
    state: directory
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: '0755'

- name: Copy jupyter lab config
  copy:
    src: jupyter_lab_config.py
    dest: "/home/{{ ansible_env.SUDO_USER }}/.jupyter/jupyter_lab_config.py"
    mode: '0644'

- name: "Copy jupyter-lab service"
  template:
    src: etc/systemd/system/jupyterlab.service.j2
    dest: /etc/systemd/system/jupyterlab.service
    owner: root
    group: root
    mode: 0644

- name: Start jupyter lab service
  systemd:
    name: jupyterlab
    enabled: yes
    daemon_reload: yes
    state: started