---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - { role: guest, tags: guest }
    - { role: network, tags: network }
    - { role: node_exporter, tags: node_exporter }
    - { role: sysprep, tags: sysprep }
