---
- name: Install libseccomp2 package
  apt:
    name: libseccomp2
    state: present

- name: Remove hyphens from build_name
  set_fact:
    build_name_no_hyphens: "{{ build_name | replace('-', '') }}"

- name: Configure nvidia driver repository
  shell: |
    wget https://developer.download.nvidia.com/compute/cuda/repos/{{ build_name_no_hyphens }}/{{ ansible_architecture }}/cuda-keyring_1.1-1_all.deb && \
    sudo dpkg -i cuda-keyring_1.1-1_all.deb

- name: Install nvidia packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - cuda-drivers
    - datacenter-gpu-manager

- name: Copy dcgm-exporter binary
  copy:
    src: usr/local/bin/dcgm-exporter-{{ binary_arch }}
    dest: /usr/local/bin/dcgm-exporter
    mode: '0755'

- name: "Copy dcgm-exporter service service"
  copy:
    src: etc/systemd/system/dcgm-exporter.service
    dest: /etc/systemd/system/dcgm-exporter.service
    owner: root
    group: root
    mode: 0644

- name: Reload systemd daemon to recognize new service
  command: systemctl daemon-reload

- name: Enable dcgm-exporter service
  systemd:
    name: dcgm-exporter
    enabled: yes

- name: Start dcgm-exporter service
  systemd:
    name: dcgm-exporter
    state: started