---
- name: Install libseccomp package
  yum:
    name: libseccomp
    state: present
    lock_timeout: 60

- name: Extract RHEL version from build_name
  set_fact:
    rhel_version: "{{ build_name | regex_search('\\d+$') }}"

- name: Configure nvidia driver repository
  shell: |
    curl -s -L https://developer.download.nvidia.com/compute/cuda/repos/rhel{{ rhel_version }}/x86_64/cuda-rhel{{ rhel_version }}.repo | \
    sudo tee /etc/yum.repos.d/cuda-rhel{{ rhel_version }}.repo
  when: ansible_architecture == "x86_64"

- name: Configure nvidia driver repository
  shell: |
    curl -s -L https://developer.download.nvidia.com/compute/cuda/repos/rhel{{ rhel_version }}/sbsa/cuda-rhel{{ rhel_version }}.repo | \
    sudo tee /etc/yum.repos.d/cuda-rhel{{ rhel_version }}.repo
  when: ansible_architecture == "aarch64"

- name: Install kernel-devel and kernel-headers
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "kernel-devel-{{ ansible_kernel }}"
    - "kernel-headers-{{ ansible_kernel }}"

- name: Install epel-release
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release

- name: Install dkms
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - dkms

- name: Install nvidia packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - nvidia-driver
    - nvidia-settings
  when: not nvidia_vgpu_driver | bool

- name: Ensure /etc/vgpu-driver directory exists on target
  file:
    path: /tmp/vgpu-driver
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: nvidia_vgpu_driver | bool

- name: Copy nvidia vGPU driver install scripts
  copy:
    src: vgpu-driver/
    dest: /tmp/vgpu-driver/
    mode: '0755'
  when: nvidia_vgpu_driver

- name: Assemble nvidia vGPU driver install script
  shell: cat NVIDIA-Linux-x86_64-550.90.07-grid.run.aa NVIDIA-Linux-x86_64-550.90.07-grid.run.ab NVIDIA-Linux-x86_64-550.90.07-grid.run.ac NVIDIA-Linux-x86_64-550.90.07-grid.run.ad > NVIDIA-Linux-x86_64-550.90.07-grid.run
  args:
    chdir: /tmp/vgpu-driver/
  when: nvidia_vgpu_driver | bool

- name: Run NVIDIA installer
  shell: bash /tmp/vgpu-driver/NVIDIA-Linux-x86_64-550.90.07-grid.run --ui=none --dkms --no-questions --kernel-source-path=/usr/src/kernels/$(ls /usr/src/kernels/)
  become: yes
  when: nvidia_vgpu_driver | bool

- name: Install dcgm packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - datacenter-gpu-manager

- name: Copy dcgm-exporter binary
  copy:
    src: usr/local/bin/dcgm-exporter-{{ binary_arch }}
    dest: /usr/local/bin/dcgm-exporter
    mode: '0755'

- name: "Copy dcgm-exporter service"
  copy:
    src: etc/systemd/system/dcgm-exporter.service
    dest: /etc/systemd/system/dcgm-exporter.service
    owner: root
    group: root
    mode: '0644'

- name: Ensure /etc/dcgm-exporter directory exists on target
  file:
    path: /etc/dcgm-exporter
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy files from local etc/dcgm-exporter to target /etc/dcgm-exporter
  copy:
    src: etc/dcgm-exporter/
    dest: /etc/dcgm-exporter/
    owner: root
    group: root
    mode: '0644'

- name: Start dcgm-exporter service
  systemd:
    name: dcgm-exporter
    enabled: yes
    daemon_reload: yes
    state: started

- name: Install fabric-manager
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - nvidia-fabric-manager
  when: fabric_manager | bool

- name: Try to relocate the PCI devices for full GPU passthrough
  command: >
    grubby --update-kernel=ALL --args="pci=nocrs,realloc"
